Feature/46 sub sidebar and sidebar new mockup ui
MetaCell/meta-diagram pull request #35
Opened 2022-10-27 15:56 UTC by emekauja

<img width="583" alt="Screenshot 2022-10-27 at 4 54 32 PM" src="https://user-images.githubusercontent.com/60346432/198339311-deecf950-b580-42aa-9ce0-9b7042f2986e.png">

2022-11-01 10:17 UTC, zsinnema approved these changes

2022-11-01 10:17 UTC, zsinnema commented
@ddelpiano do you want me to merge this one?

2022-11-01 10:20 UTC, ddelpiano commented
> @ddelpiano do you want me to merge this one?

not yet, there are the changes we discussed yesterday to be made still. Thanks!

2022-11-02 14:00 UTC, emekauja commented on src/components/Sidebar.tsx
> +  IntegratorIcon,
fixes has been updated on sidebar node

2022-11-07 11:08 UTC, ddelpiano requested changes

2022-11-07 11:08 UTC, ddelpiano commented on src/components/Sidebar.tsx
> +  const [subSelected, setSubSelected] = React.useState('Target');
remove occurence of target from meta-diagram please

2022-11-07 19:14 UTC, ddelpiano commented
@emekauja is this still required or can we close it?

2022-11-08 14:08 UTC, closed without merging